model:
  input_channels: 3
  input_size: 64
  initial_channels: 64
  num_scales: 3
  num_groups_per_scale: 20
  is_adaptive: true
  min_groups_per_scale: 1
  num_prepost_blocks: 1
  num_prepost_cells: 2
  num_cells_per_group: 2
  num_latent_per_group: 20
  num_logistic_mixtures: 10
  use_se: true
  res_dist: true

training:
  epochs: 90
  batch_size: 64
  base_lr: 0.01
  lr_min: 0.0001
  warmup_epochs: 5
  kl_anneal_portion: 0.3
  kl_const_portion: 0.0001
  weight_decay_norm: 0.1
  bn_weight_decay: 0.01
  grad_clip: 200.0
  optimizer: adamax
  weight_decay: 0.0003
